name: Deploy Dev

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set environment variables
        run: |
          echo "DB_HOST=dolado-mysql" >> .env
          echo "DB_PORT=3306" >> .env
          echo "DB_USER=${{ secrets.DB_USER }}" >> .env
          echo "DB_PASS=${{ secrets.DB_PASS }}" >> .env
          echo "DB_DEFAULT=public" >> .env
          echo "OMDB_API_KEY=${{ secrets.OMDB_API_KEY }}" >> .env

      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build docker image
        run: docker build -t caiogui/dolado-tech-challenge -f docker/dockerfiles/Dockerfile.api .

      - name: Publish image to docker hub
        run: docker push caiogui/dolado-tech-challenge:latest

  deploy:
    needs: build
    runs-on: [aws-ec2]
    steps:
      - name: Pull image from docker hub
        run: sudo docker pull caiogui/dolado-tech-challenge:latest

      - name: Run mysql container
        run: sudo docker run -d \
            --name dolado-mysql \
            -e MYSQL_ROOT_PASSWORD=password \
            -p 3306:3306 \
            -v $(pwd)/docker/volumes/mysql:/var/lib/mysql \
            mysql:8.4 \
            --mysql-native-password=ON

      - name: Run api container
        run: sudo docker run -d \
            --name dolado-api \
            --restart unless-stopped \
            -p 3000:3000 \
            -p 9229:9229 \
            -v $(pwd):/app \
            --link dolado-mysql:mysql \
            caiogui/dolado-tech-challenge:latest

